In [38]:
import kaggle as kg
import os
import pathlib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

from keras.layers import Input, Dense, BatchNormalization
from keras.models import Model
from keras.optimizers import SGD
from keras.optimizers import Adam

In [5]:
import os
from kaggle.api.kaggle_api_extended import KaggleApi

#Set environment variables for this session
os.environ['KAGGLE_USERNAME'] = 'addhyannigam'
os.environ['KAGGLE_KEY'] = 'c2236445611705b12a39948170285a63'

api = KaggleApi()
api.authenticate()  # Ensure the API uses environment variables

# Use the API to interact with Kaggle datasets

In [7]:
kg.api.authenticate()

In [8]:
kg.api.dataset_download_files(dataset="medahmedkrichen/devanagari-handwritten-character-datase",
                              path="dataset",unzip=True)

Dataset URL: https://www.kaggle.com/datasets/medahmedkrichen/devanagari-handwritten-character-datase

In [10]:
def train_test_df(path):

    img_path = list()
    img_label = list()

    for single_class_dir_path in pathlib.Path(path).glob("*"):

        for single_class_img_path in pathlib.Path(single_class_dir_path).glob("*.png"):

            img_path.append(str(single_class_img_path))
            #print(str(single_class_img_path).split("/")[-2].split("_")[-1])
            img_label.append(str(single_class_img_path).split("/")[-2].split("_")[-1])

    return pd.DataFrame(data={"img_path":img_path,"label":img_label})

In [11]:
train_path = "dataset/DevanagariHandwrittenCharacterDataset/Train"
test_path = "dataset/DevanagariHandwrittenCharacterDataset/Test"

In [12]:
training_data = train_test_df(train_path)
testing_data = train_test_df(test_path)

In [13]:
training_data

                                                img_path label
0      dataset/DevanagariHandwrittenCharacterDataset/...    ha
1      dataset/DevanagariHandwrittenCharacterDataset/...    ha
2      dataset/DevanagariHandwrittenCharacterDataset/...    ha
3      dataset/DevanagariHandwrittenCharacterDataset/...    ha
4      dataset/DevanagariHandwrittenCharacterDataset/...    ha
...                                                  ...   ...
78195  dataset/DevanagariHandwrittenCharacterDataset/...     8
78196  dataset/DevanagariHandwrittenCharacterDataset/...     8
78197  dataset/DevanagariHandwrittenCharacterDataset/...     8
78198  dataset/DevanagariHandwrittenCharacterDataset/...     8
78199  dataset/DevanagariHandwrittenCharacterDataset/...     8

[78200 rows x 2 columns]

In [14]:
testing_data

                                                img_path label
0      dataset/DevanagariHandwrittenCharacterDataset/...    ha
1      dataset/DevanagariHandwrittenCharacterDataset/...    ha
2      dataset/DevanagariHandwrittenCharacterDataset/...    ha
3      dataset/DevanagariHandwrittenCharacterDataset/...    ha
4      dataset/DevanagariHandwrittenCharacterDataset/...    ha
...                                                  ...   ...
13795  dataset/DevanagariHandwrittenCharacterDataset/...     8
13796  dataset/DevanagariHandwrittenCharacterDataset/...     8
13797  dataset/DevanagariHandwrittenCharacterDataset/...     8
13798  dataset/DevanagariHandwrittenCharacterDataset/...     8
13799  dataset/DevanagariHandwrittenCharacterDataset/...     8

[13800 rows x 2 columns]

In [15]:
character2int = dict(zip(training_data["label"].unique(),range(len(training_data["label"].unique()))))

In [16]:
character2int

{'ha': 0,
 'cha': 1,
 'la': 2,
 'gha': 3,
 '1': 4,
 'tra': 5,
 'motosaw': 6,
 '2': 7,
 'dhaa': 8,
 'chhya': 9,
 'adna': 10,
 '7': 11,
 'kha': 12,
 'bha': 13,
 'kna': 14,
 'ba': 15,
 'tha': 16,
 'ma': 17,
 'patalosaw': 18,
 '0': 19,
 'ga': 20,
 'daa': 21,
 'waw': 22,
 'pha': 23,
 'tabala': 24,
 'da': 25,
 'chha': 26,
 '5': 27,
 'ja': 28,
 '6': 29,
 'thaa': 30,
 '3': 31,
 'dha': 32,
 'ra': 33,
 'jha': 34,
 'taamatar': 35,
 '4': 36,
 'yaw': 37,
 'ka': 38,
 'na': 39,
 'pa': 40,
 'yna': 41,
 'gya': 42,
 '9': 43,
 'petchiryakha': 44,
 '8': 45}

In [17]:
training_data["label"].replace(to_replace=character2int.keys(),value=character2int.values(),
                               inplace=True)

/tmp/ipykernel_1899/2698354796.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  training_data["label"].replace(to_replace=character2int.keys(),value=character2int.values(),
/tmp/ipykernel_1899/2698354796.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  training_data["label"].replace(to_replace=character2int.keys(),value=character2int.values(),

In [18]:
training_data

                                                img_path  label
0      dataset/DevanagariHandwrittenCharacterDataset/...      0
1      dataset/DevanagariHandwrittenCharacterDataset/...      0
2      dataset/DevanagariHandwrittenCharacterDataset/...      0
3      dataset/DevanagariHandwrittenCharacterDataset/...      0
4      dataset/DevanagariHandwrittenCharacterDataset/...      0
...                                                  ...    ...
78195  dataset/DevanagariHandwrittenCharacterDataset/...     45
78196  dataset/DevanagariHandwrittenCharacterDataset/...     45
78197  dataset/DevanagariHandwrittenCharacterDataset/...     45
78198  dataset/DevanagariHandwrittenCharacterDataset/...     45
78199  dataset/DevanagariHandwrittenCharacterDataset/...     45

[78200 rows x 2 columns]

In [19]:
testing_data.replace(to_replace=character2int.keys(),value=character2int.values(),
                     inplace=True)

/tmp/ipykernel_1899/3185811566.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  testing_data.replace(to_replace=character2int.keys(),value=character2int.values(),

In [20]:
testing_data

                                                img_path  label
0      dataset/DevanagariHandwrittenCharacterDataset/...      0
1      dataset/DevanagariHandwrittenCharacterDataset/...      0
2      dataset/DevanagariHandwrittenCharacterDataset/...      0
3      dataset/DevanagariHandwrittenCharacterDataset/...      0
4      dataset/DevanagariHandwrittenCharacterDataset/...      0
...                                                  ...    ...
13795  dataset/DevanagariHandwrittenCharacterDataset/...     45
13796  dataset/DevanagariHandwrittenCharacterDataset/...     45
13797  dataset/DevanagariHandwrittenCharacterDataset/...     45
13798  dataset/DevanagariHandwrittenCharacterDataset/...     45
13799  dataset/DevanagariHandwrittenCharacterDataset/...     45

[13800 rows x 2 columns]

In [21]:
Y_true_train = to_categorical(training_data["label"],num_classes=46)

In [22]:
Y_true_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
Y_true_test = to_categorical(testing_data["label"],num_classes=46)

In [24]:
Y_true_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:

def cnn_based():
    model = Sequential([
        Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 1)),
        MaxPooling2D(pool_size=(2, 2)),
        Conv2D(64, (3, 3), activation='relu'),
        MaxPooling2D(pool_size=(2, 2)),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(46, activation='softmax')
    ])
    return model

In [46]:
def custom_data_generator(data_df, Y_true, mb_size):
    indices = np.arange(len(data_df))
    np.random.shuffle(indices)

    for i in range(len(data_df) // mb_size):
        batch_idx = indices[i * mb_size:(i + 1) * mb_size]
        X_mb = []

        for idx in batch_idx:
            img = plt.imread(data_df.iloc[idx]["img_path"])
            img = img.reshape(32, 32, 1) / 255.0  # normalize
            X_mb.append(img)

        X_mb = np.array(X_mb)
        Y_true_mb = Y_true[batch_idx]
        yield X_mb, Y_true_mb

In [28]:
epochs = 50
training_data_mb_size = 782
testing_data_mb_size = 138

In [29]:
m = cnn_based()
m.summary()

/home/addy/.local/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2025-04-30 11:10:26.917484: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:152] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 30, 30, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 15, 15, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 13, 13, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 6, 6, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 2304)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       295,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 46)             │         5,934 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 319,790 (1.22 MB)

 Trainable params: 319,790 (1.22 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
def loss_fn(Y_true_mb, Y_pred_mb):
    return tf.reduce_mean(tf.keras.losses.categorical_crossentropy(y_true=Y_true_mb, y_pred=Y_pred_mb))

optimizer = Adam(learning_rate=0.01)

In [61]:
@tf.function
def training_step(X_train_mb, Y_true_train_mb):
    with tf.GradientTape() as tape:
        Y_pred_train_mb = m(X_train_mb, training=True)
        training_loss = loss_fn(Y_true_train_mb, Y_pred_train_mb)

    grads = tape.gradient(training_loss, m.trainable_weights)
    optimizer.apply_gradients(zip(grads, m.trainable_weights))
    train_acc_metric.update_state(Y_true_train_mb, Y_pred_train_mb)

    return training_loss

In [62]:
def testing_forward_pass(X_test_mb, Y_true_test_mb):
    Y_pred_test_mb = m(X_test_mb, training=False)
    testing_loss = loss_fn(Y_true_test_mb, Y_pred_test_mb)
    test_acc_metric.update_state(Y_true_test_mb, Y_pred_test_mb)
    return testing_loss

In [63]:
epochs = 50
training_data_mb_size = 750
testing_data_mb_size = 170
train_acc_metric = tf.keras.metrics.CategoricalAccuracy()
test_acc_metric = tf.keras.metrics.CategoricalAccuracy()

In [ ]:
for epoch in range(epochs):
    training_data_generator = custom_data_generator(training_data, Y_true_train, training_data_mb_size)
    for time_step, (X_train_mb, Y_true_train_mb) in enumerate(training_data_generator):
        training_loss = training_step(X_train_mb, Y_true_train_mb)

        if (time_step + 1) % 50 == 0:
            print(f"Epoch {epoch+1}, Step {time_step+1}, Loss: {training_loss:.4f}")

    train_acc = train_acc_metric.result()
    print(f"Epoch {epoch+1}, Training Accuracy: {train_acc:.4f}")
    train_acc_metric.reset_state()

    testing_data_generator = custom_data_generator(testing_data, Y_true_test, testing_data_mb_size)
    for X_test_mb, Y_true_test_mb in testing_data_generator:
        testing_loss = testing_forward_pass(X_test_mb, Y_true_test_mb)

    test_acc = test_acc_metric.result()
    print(f"Epoch {epoch+1}, Testing Accuracy: {test_acc:.4f}, Testing Loss (last batch): {testing_loss:.4f}\n")
    test_acc_metric.reset_state()

Epoch 1, Step 50, Loss: 3.8279
Epoch 1, Step 100, Loss: 3.8273
Epoch 1, Training Accuracy: 0.0205
Epoch 1, Testing Accuracy: 0.0218, Testing Loss (last batch): 3.8240

Epoch 2, Step 50, Loss: 3.8293
Epoch 2, Step 100, Loss: 3.8292
Epoch 2, Training Accuracy: 0.0204
Epoch 2, Testing Accuracy: 0.0218, Testing Loss (last batch): 3.8284